# fly.toml app configuration file generated for sparkling-waterfall-6713 on 2023-08-15T11:55:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "patient-star-685"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
