const producerTrack = {
  _id: '7c25a58c-5efd-3654-eba8-5b198eb8f825',
  _reactTag: '7c25a58c-5efd-3654-eba8-5b198eb8f825',
  _tracks: [
    {
      _constraints: [Object],
      _enabled: true,
      _muted: false,
      _peerConnectionId: 1,
      _readyState: 'live',
      _settings: [Object],
      id: '229853ae-7c47-40d9-bada-001a0b7262cf',
      kind: 'video',
      label: '',
      remote: true,
    },
  ],
};

const consumer = {
  _appData: {},
  _closed: false,
  _events: { '@close': [], '@getstats': [], '@pause': [], '@resume': [] },
  _eventsCount: 4,
  _id: '229853ae-7c47-40d9-bada-001a0b7262cf',
  _localId: '0',
  _maxListeners: 0,
  _observer: { _events: {}, _eventsCount: 0, _maxListeners: 0 },
  _paused: false,
  _producerId: '2d70428a-fcba-4ba1-ac93-fc4d12ac7461',
  _rtpParameters: {
    codecs: [[Object], [Object]],
    encodings: [[Object]],
    headerExtensions: [[Object], [Object], [Object], [Object], [Object]],
    mid: '0',
    rtcp: { cname: '53b7f8b2', reducedSize: true },
  },
  _rtpReceiver: {
    _id: '229853ae-7c47-40d9-bada-001a0b7262cf',
    _peerConnectionId: 1,
    _rtpParameters: [Object],
    _track: {
      _constraints: [Object],
      _enabled: true,
      _muted: false,
      _peerConnectionId: 1,
      _readyState: 'live',
      _settings: [Object],
      id: '229853ae-7c47-40d9-bada-001a0b7262cf',
      kind: 'video',
      label: '',
      remote: true,
    },
  },
  _track: {
    _constraints: {},
    _enabled: true,
    _muted: false,
    _peerConnectionId: 1,
    _readyState: 'live',
    _settings: {},
    id: '229853ae-7c47-40d9-bada-001a0b7262cf',
    kind: 'video',
    label: '',
    remote: true,
  },
  onTrackEnded: [],
};

const params = {
  id: '229853ae-7c47-40d9-bada-001a0b7262cf',
  kind: 'video',
  producerId: '2d70428a-fcba-4ba1-ac93-fc4d12ac7461',
  rtpParameters: {
    codecs: [[], []],
    encodings: [[]],
    headerExtensions: [[], [], [], [], []],
    mid: '0',
    rtcp: { cname: '53b7f8b2', reducedSize: true },
  },
};

const consumerTransport = {
  _appData: {},
  _awaitQueue: { nextTaskId: 0, pendingTasks: {}, stopping: false },
  _canProduceByKind: { audio: true, video: true },
  _closed: false,
  _connectionState: 'new',
  _consumerCloseInProgress: false,
  _consumerCreationInProgress: false,
  _consumerPauseInProgress: false,
  _consumerResumeInProgress: false,
  _consumers: {},
  _dataConsumers: {},
  _dataProducers: {},
  _direction: 'recv',
  _events: {},
  _eventsCount: 0,
  _extendedRtpCapabilities: {
    codecs: [[Object], [Object], [Object]],
    headerExtensions: [
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
      [Object],
    ],
  },
  _handler: {
    _closed: false,
    _direction: 'recv',
    _events: {
      '@connect': [],
      '@connectionstatechange': [],
      '@icegatheringstatechange': [],
    },
    _eventsCount: 3,
    _hasDataChannelMediaSection: false,
    _mapMidTransceiver: {},
    _maxListeners: Infinity,
    _nextSendSctpStreamId: 0,
    _pc: {
      _pcId: 1,
      _pendingTrackEvents: [Array],
      _remoteStreams: [],
      _transceivers: [Array],
      connectionState: 'new',
      iceConnectionState: 'new',
      iceGatheringState: 'new',
      localDescription: null,
      remoteDescription: null,
      signalingState: 'stable',
    },
    _remoteSdp: {
      _dtlsParameters: [Object],
      _iceCandidates: [Array],
      _iceParameters: [Object],
      _mediaSections: [Array],
      _midToIndex: [],
      _plainRtpParameters: undefined,
      _planB: false,
      _sctpParameters: undefined,
      _sdpObject: [Object],
    },
    _sendStream: {
      _id: 'd1c647d8-1298-c098-205e-d77807df35c8',
      _reactTag: 'd1c647d8-1298-c098-205e-d77807df35c8',
      _tracks: [Array],
    },
    _sendingRemoteRtpParametersByKind: { audio: [Object], video: [Object] },
    _sendingRtpParametersByKind: { audio: [Object], video: [Object] },
    _transportReady: false,
  },
  _iceGatheringState: 'new',
  _id: '47744e42-2cad-4356-8080-874778bf362b',
  _maxListeners: Infinity,
  _maxSctpMessageSize: null,
  _observer: { _events: {}, _eventsCount: 0, _maxListeners: Infinity },
  _pendingCloseConsumers: {},
  _pendingConsumerTasks: [],
  _pendingPauseConsumers: {},
  _pendingResumeConsumers: {},
  _probatorConsumerCreated: false,
  _producers: {},
};

const transportParams = {
  dtlsParameters: {
    fingerprints: [[Object], [Object], [Object], [Object], [Object]],
    role: 'auto',
  },
  iceCandidates: [
    {
      address: '127.0.0.1',
      foundation: 'udpcandidate',
      ip: '127.0.0.1',
      port: 40000,
      priority: 1076558079,
      protocol: 'udp',
      type: 'host',
    },
    {
      address: '127.0.0.1',
      foundation: 'tcpcandidate',
      ip: '127.0.0.1',
      port: 40000,
      priority: 1076276479,
      protocol: 'tcp',
      tcpType: 'passive',
      type: 'host',
    },
  ],
  iceParameters: {
    iceLite: true,
    password: '45q1xtkmd06r1nlsp2vimetru9foik6x',
    usernameFragment: 'yf4jzvmwz2opb9bifct440jh0f1mwqwn',
  },
  id: '47744e42-2cad-4356-8080-874778bf362b',
};

const deviceCapabilities = {
  codecs: [
    {
      channels: 2,
      clockRate: 48000,
      kind: 'audio',
      mimeType: 'audio/opus',
      parameters: [Object],
      preferredPayloadType: 100,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/VP8',
      parameters: [Object],
      preferredPayloadType: 101,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 102,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/H264',
      parameters: [Object],
      preferredPayloadType: 107,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 108,
      rtcpFeedback: [Array],
    },
  ],
  headerExtensions: [
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 1,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:mid',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 1,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:mid',
    },
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 4,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 4,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 5,
      uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01',
    },
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 10,
      uri: 'urn:ietf:params:rtp-hdrext:ssrc-audio-level',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 11,
      uri: 'urn:3gpp:video-orientation',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 12,
      uri: 'urn:ietf:params:rtp-hdrext:toffset',
    },
  ],
};

const routerCapabilities = {
  codecs: [
    {
      channels: 2,
      clockRate: 48000,
      kind: 'audio',
      mimeType: 'audio/opus',
      parameters: [Object],
      preferredPayloadType: 100,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/VP8',
      parameters: [Object],
      preferredPayloadType: 101,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 102,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/VP9',
      parameters: [Object],
      preferredPayloadType: 103,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 104,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/H264',
      parameters: [Object],
      preferredPayloadType: 105,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 106,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/H264',
      parameters: [Object],
      preferredPayloadType: 107,
      rtcpFeedback: [Array],
    },
    {
      clockRate: 90000,
      kind: 'video',
      mimeType: 'video/rtx',
      parameters: [Object],
      preferredPayloadType: 108,
      rtcpFeedback: [Array],
    },
  ],
  headerExtensions: [
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 1,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:mid',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 1,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:mid',
    },
    {
      direction: 'recvonly',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 2,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id',
    },
    {
      direction: 'recvonly',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 3,
      uri: 'urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id',
    },
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 4,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 4,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time',
    },
    {
      direction: 'recvonly',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 5,
      uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 5,
      uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 6,
      uri: 'http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 7,
      uri: 'urn:ietf:params:rtp-hdrext:framemarking',
    },
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 10,
      uri: 'urn:ietf:params:rtp-hdrext:ssrc-audio-level',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 11,
      uri: 'urn:3gpp:video-orientation',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 12,
      uri: 'urn:ietf:params:rtp-hdrext:toffset',
    },
    {
      direction: 'sendrecv',
      kind: 'audio',
      preferredEncrypt: false,
      preferredId: 13,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time',
    },
    {
      direction: 'sendrecv',
      kind: 'video',
      preferredEncrypt: false,
      preferredId: 13,
      uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-capture-time',
    },
  ],
};

