name: App Controller

on:
  push:
    branches: ['main', 'develop']

jobs:
  whats-changed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: updated-packages
        uses: vgpastor/monorepo-updated-packages@v1.3
        with:
          folder: ./

      - name: Build backend
        if: contains(steps.updated-packages.outputs.packages, 'server')
        run: echo "backend"

      - name: Build frontend
        if: contains(steps.updated-packages.outputs.packages, 'client')
        run: echo "frontend"


